from typing import Any

def proposal_parse(data: bytes, current_epoch: int) -> str: ...
def votes_parse(data: bytes) -> str: ...
def proposal_result_parse(data: bytes) -> str: ...
def commission_pair_parse(data: bytes) -> str: ...
def address_parse(data: bytes) -> str: ...
